name: cet_msa
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - pyyaml
  - tqdm
  - pip:
      - torch==1.11.0
      - torchvision==0.12.0